{% set name = "jive" %}
{% set version = "7.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/jive/-/archive/{{ version }}/jive-{{ version }}.tar.gz
  sha256: bda78a175a6cda64cbb3e748ba726c2cd3cfe6f500c3d02f751885c8f778e28b

build:
  number: 0

requirements:
  build:
    - openjdk 8
    - maven
  run:
    - openjdk >=8

test:
  commands:
    - jive -h
    - test -f ${PREFIX}/share/java/Jive.jar             # [unix]
    - test -f ${PREFIX}/bin/jive                        # [unix]
    - if not exist %PREFIX%\share\java\Jive.jar exit 1  # [win]
    - if not exist %PREFIX%\Scripts\jive.bat exit 1     # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html
  summary: Jive is a standalone JAVA application designed to browse and edit the static TANGO database.
  dev_url: https://gitlab.com/tango-controls/jive
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/built-in/jive/index.html

extra:
  recipe-maintainers:
    - beenje
